@echo off
if exist %windir%\System32\WindowsPowerShell\v1.0\powershell.exe (
  title Starting PowerShell x64...
  echo Starting PowerShell x64...
  title PowerShell x64 In CMD
  %windir%\System32\WindowsPowerShell\v1.0\powershell.exe
) else (
  title Starting PowerShell x86...
  echo Starting PowerShell x86...
  title PowerShell x86 In CMD
  %windir%\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
)
