name: Run a example Batch script

on:
  push:
 
jobs:
 run_script:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2.4.0
     - name: Run a example PowerShell In CMD Batch script
       working-directory: ./Batch-Files/PowerShell/
       run: PowerShell_In_CMD.bat
       shell: cmd
